/**
 * Invite response interop vectors between TypeScript and Rust.
 */
import { describe, it, expect } from "vitest"
import { getEventHash, getPublicKey, nip44 } from "nostr-tools"
import { getConversationKey } from "nostr-tools/nip44"
import { bytesToHex, hexToBytes } from "@noble/hashes/utils"
import * as fs from "fs"
import * as path from "path"
import { fileURLToPath } from "url"

import { Invite } from "../src/Invite"
import { decryptInviteResponse } from "../src/inviteUtils"
import { INVITE_RESPONSE_KIND, MESSAGE_EVENT_KIND, type NostrEvent } from "../src/types"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const INVITER_DEVICE_SK = hexToBytes("1111111111111111111111111111111111111111111111111111111111111111")
const INVITER_EPHEMERAL_SK = hexToBytes("2222222222222222222222222222222222222222222222222222222222222222")
const INVITEE_DEVICE_SK = hexToBytes("3333333333333333333333333333333333333333333333333333333333333333")
const INVITEE_OWNER_SK = hexToBytes("4444444444444444444444444444444444444444444444444444444444444444")
const SHARED_SECRET = "5555555555555555555555555555555555555555555555555555555555555555"
const INVITE_CREATED_AT = 1_700_300_000

interface InviteResponseVector {
  description: string
  invite_created_at: number
  inviter_device_sk: string
  inviter_device_pubkey: string
  inviter_ephemeral_sk: string
  inviter_ephemeral_pubkey: string
  shared_secret: string
  invitee_device_sk: string
  invitee_device_pubkey: string
  invitee_owner_pubkey?: string
  invitee_session_pubkey: string
  invite_response_event: NostrEvent
  expected: {
    invitee_identity: string
    invitee_session_pubkey: string
    owner_public_key?: string
  }
}

function vectorPath(filename: string): string {
  return path.join(__dirname, "../../test-vectors", filename)
}

function assertInnerRumor(vector: InviteResponseVector): void {
  const innerJson = nip44.decrypt(
    vector.invite_response_event.content,
    getConversationKey(hexToBytes(vector.inviter_ephemeral_sk), vector.invite_response_event.pubkey)
  )
  const inner = JSON.parse(innerJson)

  expect(inner.id).toBe(getEventHash(inner))
  expect(inner.pubkey).toBe(vector.invitee_device_pubkey)
  expect(inner.kind).toBe(MESSAGE_EVENT_KIND)
  expect(inner.tags).toEqual([])
  expect(typeof inner.content).toBe("string")
  expect(inner.content.length).toBeGreaterThan(0)
}

async function buildTypeScriptVector(): Promise<InviteResponseVector> {
  const inviterDevicePubkey = getPublicKey(INVITER_DEVICE_SK)
  const inviterEphemeralPubkey = getPublicKey(INVITER_EPHEMERAL_SK)
  const inviteeDevicePubkey = getPublicKey(INVITEE_DEVICE_SK)
  const inviteeOwnerPubkey = getPublicKey(INVITEE_OWNER_SK)

  const invite = new Invite(
    inviterEphemeralPubkey,
    SHARED_SECRET,
    inviterDevicePubkey,
    INVITER_EPHEMERAL_SK,
    undefined,
    undefined,
    [],
    INVITE_CREATED_AT,
  )
  const { session, event } = await invite.accept(
    inviteeDevicePubkey,
    INVITEE_DEVICE_SK,
    inviteeOwnerPubkey,
  )
  const inviteeSessionPubkey = session.state.ourCurrentNostrKey?.publicKey
  if (!inviteeSessionPubkey) {
    throw new Error("invite accept did not create an invitee session pubkey")
  }

  return {
    description: "Invite response vector generated by TypeScript",
    invite_created_at: INVITE_CREATED_AT,
    inviter_device_sk: bytesToHex(INVITER_DEVICE_SK),
    inviter_device_pubkey: inviterDevicePubkey,
    inviter_ephemeral_sk: bytesToHex(INVITER_EPHEMERAL_SK),
    inviter_ephemeral_pubkey: inviterEphemeralPubkey,
    shared_secret: SHARED_SECRET,
    invitee_device_sk: bytesToHex(INVITEE_DEVICE_SK),
    invitee_device_pubkey: inviteeDevicePubkey,
    invitee_owner_pubkey: inviteeOwnerPubkey,
    invitee_session_pubkey: inviteeSessionPubkey,
    invite_response_event: event as NostrEvent,
    expected: {
      invitee_identity: inviteeDevicePubkey,
      invitee_session_pubkey: inviteeSessionPubkey,
      owner_public_key: inviteeOwnerPubkey,
    },
  }
}

async function loadOrGenerateTypeScriptVector(): Promise<InviteResponseVector> {
  const outputPath = vectorPath("ts-invite-response-vectors.json")
  if (process.env.REGENERATE_VECTORS !== "true" && fs.existsSync(outputPath)) {
    return JSON.parse(fs.readFileSync(outputPath, "utf-8"))
  }

  const vector = await buildTypeScriptVector()
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, JSON.stringify(vector, null, 2))
  return vector
}

describe("Invite response interop vectors", () => {
  it("generates and validates the TypeScript invite response vector", async () => {
    const vector = await loadOrGenerateTypeScriptVector()

    expect(vector.invite_response_event.kind).toBe(INVITE_RESPONSE_KIND)
    expect(vector.invite_response_event.tags).toContainEqual(["p", vector.inviter_ephemeral_pubkey])
    assertInnerRumor(vector)

    const decoded = await decryptInviteResponse({
      envelopeContent: vector.invite_response_event.content,
      envelopeSenderPubkey: vector.invite_response_event.pubkey,
      inviterEphemeralPrivateKey: hexToBytes(vector.inviter_ephemeral_sk),
      inviterPrivateKey: hexToBytes(vector.inviter_device_sk),
      sharedSecret: vector.shared_secret,
    })

    expect(decoded.inviteeIdentity).toBe(vector.expected.invitee_identity)
    expect(decoded.inviteeSessionPublicKey).toBe(vector.expected.invitee_session_pubkey)
    expect(decoded.ownerPublicKey).toBe(vector.expected.owner_public_key)
  })

  it("decrypts the Rust invite response vector", async () => {
    const rustVectorPath = vectorPath("rust-invite-response-vectors.json")
    if (!fs.existsSync(rustVectorPath)) {
      console.log("Rust invite response vector not found, skipping...")
      return
    }
    const vector: InviteResponseVector = JSON.parse(fs.readFileSync(rustVectorPath, "utf-8"))
    assertInnerRumor(vector)

    const decoded = await decryptInviteResponse({
      envelopeContent: vector.invite_response_event.content,
      envelopeSenderPubkey: vector.invite_response_event.pubkey,
      inviterEphemeralPrivateKey: hexToBytes(vector.inviter_ephemeral_sk),
      inviterPrivateKey: hexToBytes(vector.inviter_device_sk),
      sharedSecret: vector.shared_secret,
    })

    expect(decoded.inviteeIdentity).toBe(vector.expected.invitee_identity)
    expect(decoded.inviteeSessionPublicKey).toBe(vector.expected.invitee_session_pubkey)
    expect(decoded.ownerPublicKey).toBe(vector.expected.owner_public_key)
  })
})
